name: pull-request-review

on:
  pull_request:
    types:
      - synchronize
      - labeled
      - assigned
      - opened
    paths:
      - 'src/**'
    branches:
      - feature/*
      - sp*
      - step*

jobs:
  eslint:
    if: >
      github.event.pull_request.assignee != null &&
      (
        contains(github.event.pull_request.labels.*.name, 'draft') ||
        contains(github.event.pull_request.labels.*.name, 'review')
      )
    name: eslint checker
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: npm install --legacy-peer-deps
      - name: Run eslint
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.github_token }}
          node_options: "--max_old_space_size=8192"
          reporter: github-check
          workdir: "./"
          eslint_flags: "--no-eslintrc -c .eslintrc.json src/"

  misspell:
    if: >
      github.event.pull_request.assignee != null &&
      (
        contains(github.event.pull_request.labels.*.name, 'draft') ||
        contains(github.event.pull_request.labels.*.name, 'review')
      )
    name: misspell checker
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v2
      - name: Check misspell
        uses: reviewdog/action-misspell@v1
        with:
          github_token: ${{ secrets.github_token }}