name: pull-request-target

on:
  pull_request_target:
    types:
      - labeled
      - unlabeled

jobs:
  sample-job:
    if: github.event.action == 'labeled'
    runs-on: ubuntu-latest
    steps:
      - name: labeled
        uses: actions/checkout@v2

      - if: contains(github.event.label.name, 'review')
        run: echo "labeled review"

      - if: contains(github.event.label.name, 'draft')
        run: echo "labeled draft"

  sample-job2:
    if: github.event.action == 'unlabeled'
    runs-on: ubuntu-latest
    steps:
      - name: unlabeled
        uses: actions/checkout@v2

      - if: contains(github.event.label.name, 'review')
        run: echo "unlabeled review"

      - if:  contains(github.event.label.name, 'draft')
        run: echo "unlabeled draft"