name: pull-request-target

on:
  pull_request_target:
    types: [
      opened,
      synchronize,
      reopened,
      ready_for_review,
      review_requested,
      review_request_removed,
      labeled,
      unlabeled,
      edited,
    ]

jobs:
  sample-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - if: github.event.action == 'labeled'
        run: echo "labeled"

      - if: github.event.action == 'labeled' && contains(github.event.label.name, 'review')
        run: echo "labeled review"

      - if: github.event.action == 'unlabeled' && contains(github.event.label.name, 'draft')
        run: echo "unlabeled draft"