name: pull-request-target

on:
  pull_request_target:
    types:
      - labeled
      - unlabeled

jobs:
  sample-job:
    if: |
      contains(github.event.pull_request.labels.*.name, 'draft') ||
      contains(github.event.pull_request.labels.*.name, 'review') ||
      ( contains(github.event.label.name, 'draft') &&
        github.event.action == 'labeled' ) ||
      ( contains(github.event.label.name, 'review') &&
        github.event.action == 'labeled' )

    runs-on: ubuntu-latest
    steps:
      - name: labeled
        uses: actions/checkout@v2

      - if: contains(github.event.pull_request.labels.*.name, 'draft')
        run: echo "includes draft"

      - if: contains(github.event.pull_request.labels.*.name, 'review')
        run: echo "includes review"

      - if: contains(github.event.label.name, 'review')
        run: echo "labeled review"

      - if: contains(github.event.label.name, 'draft')
        run: echo "labeled draft"