name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - run: echo "this is a test"
      - uses: actions/checkout@v2
      - run: |
          ls -la
          pwd
          cd .git