name: pull-request-target
on:
  pull_request_target:
    types: [
      opened,
      synchronize,
      reopened,
      ready_for_review,
      review_requested,
      review_request_removed,
      labeled,
      unlabeled,
      edited,
    ]

jobs:
  sample-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 100
          ref: ${{ github.head_ref }}

      - run: echo "${github.repository_owner}"

      # - id: ready_for_review
      #   if: github.event.action == 'ready_for_review'
      #   run: echo "ready_for_review"

      - id: labeled
        if: github.event.action == 'labeled'
        run: echo "labeled"
      - id: check-labeled
        if: github.event.action == 'labeled' && contains(github.event.label.name, 'review')
        run: echo "labeled review"

      - id: unlabeled
        if: github.event.action == 'unlabeled' && contains(github.event.label.name, 'draft')
        run: echo "unlabeled draft"